# Generated by Django 5.0.7 on 2024-08-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='is_liked',
            field=models.BooleanField(null=True),
        ),
    ]
