# Generated by Django 5.0.7 on 2024-08-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_dislikes_remove_post_likes_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='is_liked',
            field=models.BooleanField(default=True),
        ),
    ]
