# Generated by Django 5.0.7 on 2024-08-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_vote_is_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='is_liked',
            field=models.BooleanField(),
        ),
    ]
