# Generated by Django 5.0.7 on 2024-08-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_hashtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.hashtag'),
        ),
    ]
